### ISSUE TITLE
Bagus, tetapi perlu perbaikan

### ISSUE THREAD

**Issue by ekaputra07** [rociretama/LatihanJavaBaru#1]
Sepertinya kurang divalidasi, ketika inputnya masih kosong, saya klik tombolnya, dia error:
![Screen Shot 2021-03-19 at 9 38 54 am](https://user-images.githubusercontent.com/1094221/111706817-0f1e1100-8897-11eb-9d05-c146c9a02d05.png)

Kenapa saya bisa pilih cewek dan cowok sekaligus ya? hehe
![Screen Shot 2021-03-19 at 9 39 18 am](https://user-images.githubusercontent.com/1094221/111706821-10e7d480-8897-11eb-8657-6ca4a03ed244.png)

Saya salut, meski susah tidak menyerah. ciri2 programmer hebat nanti 👍

**Comment by rociretama** [comment]
https://github.com/rociretama/LatihanJavaBaru/blob/dbf27b3842459958276b561dc2f66874b51a1d28/AppPenghitungBeratBadanIdeal.jar yg sudah diperbaiki bg ^_^, seru!
